services:
  spellcards-app:
    image: spellcards-app:local
    build:
      context: .
      dockerfile: spellcards-app/Dockerfile
    restart: unless-stopped

  spellcards-web:
    image: spellcards-web:local
    build:
      context: .
      dockerfile: spellcards-web/Dockerfile
    depends_on:
      - spellcards-app
    restart: unless-stopped
